#! /bin/bash
cd /e/zw/PythonScripts
git add E:/zw/Zweihander/Content/UniversalCharacterSystem/Misc/Preview_Scene/HDRI
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Roll_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Roll_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Roll_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Round_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Round_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Round_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Tile_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Tile_003_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cheese_Tile_003_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Chicken_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Chicken_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Chicken_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_Pattern_001.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_Pattern_002.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_Pattern_003.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_Pattern_004.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Cloth_Pattern_005.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_003_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_003_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_004_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_004_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Crate_004_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Garlic_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Garlic_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Garlic_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grains_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grains_003_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grains_003_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_004_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_004_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_004_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_005_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_005_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Grans_005_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Hook_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Hook_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Hook_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Jar_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Jar_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Jar_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Metal_Detailmap_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Onion_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Onion_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Onion_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Onion_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Onion_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Onion_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pack_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pack_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pack_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pear_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pear_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pear_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_004_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_004_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_005_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_006_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pepper_Tile_007_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranate_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranate_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranate_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranate_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranate_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranate_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranit_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranit_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pomegranit_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pork_Belly_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pork_Belly_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pork_Belly_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Potato_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pumpkin_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pumpkin_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Pumpkin_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rope_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rope_001_H.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rope_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rope_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rusty_Metal_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rusty_Metal_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Rusty_Metal_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_Open_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_Open_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sack_Open_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sausage_Fresh_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sausage_Fresh_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Sausage_Fresh_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Scale_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Scale_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Scale_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_003_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Board_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Board_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Board_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Board_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Board_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Board_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Cloth_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Cloth_003_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Cloth_003_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Cloth_Decoration_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Cloth_Decoration_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stall_Cloth_Decoration_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stucco_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stucco_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Stucco_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_003_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_003_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_004_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_004_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tag_004_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tomatoes_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tomatoes_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Tomatoes_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Walnuts_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Walnuts_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Walnuts_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Water_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Waved_Basket_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Waved_Basket_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Waved_Basket_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_002_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_002_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wicker_Tile_003_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Board_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Board_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Board_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Damaged_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Damaged_001_H.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Damaged_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Damaged_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Detailmap_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Detailmap_002_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Planks_001_C.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Planks_001_C_Stain.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Planks_001_N.uasset
git add E:/zw/Zweihander/Content/MedievalMarket/Textures/T_Wood_Planks_001_S.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Axe/M_Axe.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Axe/SM_Axe_1.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Axe/SM_Axe_1_DefaultMaterial_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Axe/SM_Axe_1_DefaultMaterial_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Axe/SM_Axe_1_DefaultMaterial_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Barrel/Barrel_1A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Barrel/Barrel_1A_DefaultMaterial_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Barrel/Barrel_1A_DefaultMaterial_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Barrel/Barrel_1A_DefaultMaterial_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Barrel/M_BarreL_1A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bench/Bench.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bench/Bench_M_Bench_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bench/Bench_M_Bench_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bench/Bench_M_Bench_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bench/M_Bench.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bottles/Bottle_07/M_Bottle_07.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bottles/Bottle_07/SM_Bootle_07_DefaultMaterial_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bottles/Bottle_07/SM_Bootle_07_DefaultMaterial_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bottles/Bottle_07/SM_Bootle_07_DefaultMaterial_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Bottles/Bottle_07/SM_Bottle_07.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Coin/M_GoldCoin.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Coin/SM_GoldCoin.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Coin/SM_GoldCoin_M_GoldCoin_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Coin/SM_GoldCoin_M_GoldCoin_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_01/Crate_1A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_01/Crate_1A_M_Crate_1A_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_01/Crate_1A_M_Crate_1A_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_01/Crate_1A_M_Crate_1A_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_01/M_Crate_1A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_02/Crate_2A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_02/Crate_2A_M_Crate_2A_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_02/Crate_2A_M_Crate_2A_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_02/Crate_2A_M_Crate_2A_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_02/M_Crate_2A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_03/Crate_3A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_03/Crate_3A_M_Crate_3A_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_03/Crate_3A_M_Crate_3A_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_03/Crate_3A_M_Crate_3A_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Crate_03/M_Crate_3A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Aple/BC_FruitAple.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Aple/M_FruitAple_001.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Aple/N_FruitAple.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Aple/PK_FruitAple.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Aple/SM_FruitAple.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Lemon/M_Lemon.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Lemon/M_Lemon_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Lemon/SM_Lemon.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Lemon/SM_Lemon_DefaultMaterial_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Lemon/SM_Lemon_DefaultMaterial_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Orange/M_Orange.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Orange/M_Orange_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Orange/SM_Orange.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Orange/SM_Orange_M_Orange_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Orange/SM_Orange_M_Orange_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Orange/SM_Orange_M_Orange_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Peach/M_Peach.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Peach/SM_Peach.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Peach/SM_Peache_M_Peach_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Peach/SM_Peache_M_Peach_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Peach/SM_Peache_M_Peach_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Pomegranate/M_Pomegranate_01.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Pomegranate/Pomegranate_01_DefaultMaterial_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Pomegranate/Pomegranate_01_DefaultMaterial_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Pomegranate/Pomegranate_01_DefaultMaterial_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Pomegranate/SM_Pomegranate_01.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Tomato/M_Tomato.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Tomato/M_Tomato_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Tomato/SM_Tomato.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Tomato/SM_Tomato_M_Tomato_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Tomato/SM_Tomato_M_Tomato_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Fruit/Tomato/SM_Tomato_M_Tomato_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/GroupedMeshes/SM_GroupCoins.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/KiteShield.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/KiteShield_M_kiteShiled_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/KiteShield_M_kiteShiled_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/M_KiteShield.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/M_kiteShiled_2.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/Textures1/KiteShield_M_kiteShiled_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/Textures1/KiteShield_M_kiteShiled_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/KiteShield/Textures1/KiteShield_M_kiteShiled_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/MarketCarpet/M_MarketCarpet.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/MarketCarpet/MarketCarpet.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/MarketCarpet/MarketCarpet_M_MarketCarpet_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/MarketCarpet/MarketCarpet_M_MarketCarpet_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/MarketCarpet/MarketCarpet_M_MarketCarpet_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Spear/M_Spear.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Spear/SM_Spear_01.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Spear/SM_Spear_01_DefaultMaterial_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Spear/SM_Spear_01_DefaultMaterial_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Spear/SM_Spear_01_DefaultMaterial_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Table_01/M_Table_02.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Table_01/SM_Table_02.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Table_01/SM_Table_02_M_Table_02_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Table_01/SM_Table_02_M_Table_02_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Table_01/SM_Table_02_M_Table_02_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/BP_MarketTent_01.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/M_Market_Tent_Cloth_1A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/M_Market_Tent_Wood_1A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/Market_Tent_1A_M_Market_Tent_Cloth_1A_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/Market_Tent_1A_M_Market_Tent_Cloth_1A_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/Market_Tent_1A_M_Market_Tent_Cloth_1A_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/Market_Tent_1A_M_Market_Tent_Wood_1A_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/Market_Tent_1A_M_Market_Tent_Wood_1A_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/Market_Tent_1A_M_Market_Tent_Wood_1A_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/SK_MarketTent_1A_P1.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/SK_MarketTent_1A_P1_SM_MarketTent_1A_P1_PhysicsAsset.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_01/SM_MarketTent_1A_P2.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/BP_MarketTent_2.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/M_Market_Tent_Cloth1_2A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/M_Market_Tent_Cloth2_2A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/M_Market_Tent_Wood_2A.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/MarketTent_2A1.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/MarketTent_2A2.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/MarketTent_2AW.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Cloth1_2B_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Cloth1_2B_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Cloth1_2B_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Cloth2_2B_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Cloth2_2B_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Cloth2_2B_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Wood_2B_BaseColor.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Wood_2B_Normal.uasset
git add E:/zw/Zweihander/Content/MedievalMarketPack/MarketAssets/Tent_02/Market_Tent_2A_M_Market_Tent_Wood_2B_OcclusionRoughnessMetallic.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_Tiles_02_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_Tiles_02_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_bark_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_bark_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_parvement_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_parvement_01_basic_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_parvement_03_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_parvement_03_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basicREDish.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basicREDish_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basicREDish_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basicREDish_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basic_YELLOW.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_01_basic_YELLOW_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_02_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_02_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_02_basic_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_plaster_wall_02_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_roof_shingles_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_roof_shingles_01_basic_InstCASTLE.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_roof_shingles_01_basic_InstGREEN.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_roof_shingles_01_basic_InstGREEN_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_roof_shingles_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_MI_Column_02.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_BIGWALL_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_BIGWALL_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_InstCobble.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_InstCobble_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_InstCobble_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Column01.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst1DARK.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst1DARK_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst1DARK_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst1DARK_Inst_InstTRIM7.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst1DARK_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHT_WALLS_Inst_Inst2.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLIGHTvlROUND.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLTRIM1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLTRIMFLOORBRicks.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLTRIM_InstBattlement1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicLTRI_column02.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_BIG.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst2.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst2_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst2_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst2_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_Inst_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basic_darkfoundation.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicfoundationSTONE.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicfoundationSTONE2_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_01_basicfoundationSTONE2_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_0211_basicLarch.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_InstFAT.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_InstFAT_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_Inst_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_stone_wall_02_basic_Inst_Inst_Inst_Inst_Inst_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood-old_modernwood_old_01_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst_Inst_Inst1_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst_Inst_Inst1_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_01_basic_Inst_Inst_Inst2.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_02_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_02_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_03_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_mossy_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_mossy_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_mossy_01_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_PLANK-ZERO.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_PLANK-ZERO_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_PLANKDARK.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_PLANK_Inst25_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_WOODPLANKS_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_WOODPLANKS_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basicBEAM_Inst25.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basicBEAM_InstDARK.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_InstZERO.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_InstZERO_OLD.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_InstZERO_OLD_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basic_MOSS_INST.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_old_01_basicrealBEAM_Inst25_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_oldfloorred.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_oldfloorred_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_oldfloorred_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_01_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_01_basic_Inst_25.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_01_basic_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_01_basic_Inst_Inst1.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_02_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_03_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_03_basic_acaciatexture.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_03_basic_acaciatexture_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_03_basic_acaciatexture_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_03_basic_acaciatexture_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_04_basic_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_04_basic_Inst25.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Basic_Instances/M_wood_planks_04_basic_Inst25_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Displacement_Instances/M_parvment_01_disp_inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Displacement_Instances/M_parvment_01_dispfireplace.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Displacement_Instances/M_wall_stone_01_disp_inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Displacement_Instances/M_wall_stone_01_disp_inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Displacement_Instances/M_wall_stone_01_disp_inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Instances/Displacement_Instances/M_wall_stone_01_disp_inst_Inst_Inst_Inst.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Master/M_basic_master.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Materials/Master/M_displacement_master.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_bark_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_bark_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_bark_01_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_floor_parvment_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_floor_parvment_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_floor_parvment_01_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_floor_parvment_02_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_floor_parvment_02_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_floor_parvment_02_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_ground_parvement_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_ground_parvement_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_ground_parvement_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_plaster_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_plaster_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_plaster_02_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_plaster_02_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_plaster_02_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_plaster_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_roof_shingles_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_roof_shingles_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_roof_shingles_01_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_01_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_01_light.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_02_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_02_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_stone_wall_02_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_tiles_02_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_tiles_02_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_tiles_02_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_01_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_02_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_02_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_02_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_03_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_03_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_03_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_moss_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_moss_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_moss_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_old_01_D.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_old_01_N.uasset
git add E:/zw/Zweihander/Content/MedievalMaterialPack/Textures/t_wood_old_01_RAOH.uasset
git add E:/zw/Zweihander/Content/MedievalPropsPack/Materials/M_Bar_Platform.uasset
git add E:/zw/Zweihander/Content/MedievalPropsPack2/Materials/BaseMaterial/FX_efeects.uasset
git add E:/zw/Zweihander/Content/Medieval_Worshop_01/DemoContent/Textures/T_Tower_01_Metallic_01.uasset
git add E:/zw/Zweihander/Content/MerlinsCave/Textures/T_WSC_Variation02.uasset
git add E:/zw/Zweihander/Content/Middle_Age_Village_Houses/Maps/Map_MedievalVillage_sharedassets/Global_ground_a_LayerInfo.uasset && exit
