#! /bin/bash
cd /e/zw/PythonScripts
git add E:/zw/Zweihander/Content/SharurCatacombsPack/Textures/s03column_albedo_01.uasset
git add E:/zw/Zweihander/Content/SharurCatacombsPack/Textures/s03column_roughness_01.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_RockCliff_01.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_RockCliff_02.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_RockCliff_03.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_RockSmooth_00.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_RockSmooth_01.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_SnowRock_01.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_SnowRock_02.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_SnowRock_02_02.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_SnowRock_05.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_Volcanic_Cliff_03.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/StaticMeshes/sm_Volcanic_Cliff_04.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_00_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_00_Height.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_00_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_00_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_01_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_01_Height.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_01_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_JungleCliff_01_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_01_d.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_01_n.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_01_rgb.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Moss_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Mud_00_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Mud_00_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Mud_00_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_NoiseDetail_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_NoiseMasks_01.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_01_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_01_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_01_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_01_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_03_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_03_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_03_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_03_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_04_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_04_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_04_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockBoulder_04_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_01_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_01_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_01_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_01_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_02_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_02_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_02_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_02_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_03_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_03_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_03_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockCliff_03_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_00_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_00_Height.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_00_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_00_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_01_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_01_Height.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_01_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSmooth_01_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSurface_00_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSurface_00_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockSurface_00_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_02_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_02_Height.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_02_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_02_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_03_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_03_Heightmap.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_03_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_03_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_Height.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_RockTiling_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Rock_DetailNormal_02.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Rock_Detail_02_n.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Rock_Detail_B_n.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Scatter_Rock_01_d.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Scatter_Rock_01_n.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Scatter_Rock_01_rgb.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SoilDamp_00_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SoilDamp_00_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SoilDamp_00_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SoilMossy_00_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SoilMossy_00_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SoilMossy_00_RGB.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_SpeckleMask_01.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerMoss_01_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerMoss_01_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerMoss_01_RMO.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerRock_01_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerRock_01_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerRock_01_RMO.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerRock_07_BaseColor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerRock_07_Normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_TowerRock_07_RMO.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_01_d.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_01_n.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_01_o.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_01_rgb.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_02_d.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_02_n.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_02_rgb.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_03_o.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_Volcanic_Cliff_04_o.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_01_basecolor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_01_multi.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_01_normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_07_basecolor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_07_multi.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_07_normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_08_basecolor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_08_multi.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_08_normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_big_01_basecolor.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_big_01_multi.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_caverock_big_01_normal.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_01_eca.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_01_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_01_os_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_02_eca.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_02_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_02_os_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_05_eca.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_05_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_05_os_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_tile_01_albedo.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_tile_01_multi.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_tile_01_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_tile_02_albedo.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_tile_02_multi.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_rock_tile_02_normals.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_snow_01_albedo.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_snow_01_hrb.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_snow_02_albedo.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_snow_02_hrb.uasset
git add E:/zw/Zweihander/Content/SharursUltimateRocks/Textures/txt_snowflake_01_normals.uasset
git add E:/zw/Zweihander/Content/ShipsAndRocks/Blueprints/BP_ball_glowing.uasset
git add E:/zw/Zweihander/Content/ShipsAndRocks/Materials/MI_metallic_hull.uasset
git add E:/zw/Zweihander/Content/SmartSplineGen/Blueprints/InternalLogic/SplineTarget_BP.uasset
git add E:/zw/Zweihander/Content/UltimateRiverTool/ParameterCollections/MPC_Landscape_Material.uasset && exit
